[package]
name = "rustynet"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.13.0"
async-std = "1.13.2"
flate2 = "1.1.8"
httpdate = "1.0.3"
toml = "0.9.11"
serde = {version = "1.0.228", features = ["derive"]}
